version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: src/dockerfile

    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tasks_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]

volumes:
  postgres_data:
